### Numpy 연습문제

In [3]:
import numpy as np

In [11]:
# 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오. 
# 10 20 30 40
# 50 60 70 80

np.arange(1,9).reshape(2,4) * 10
np.arange(10,90,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [4]:
# 2. 다음 행렬과 같은 행렬이 있다. m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
# 1)이 행렬에서 값 7 을 인덱싱한다.
# 2)이 행렬에서 값 14 을 인덱싱한다.
# 3)이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# 4)이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# 5)이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

m = np.arange(15).reshape(3,5)
m[1,2], m[-1,-1], m[1:2,1:3], m[1:,2:3]

(7,
 14,
 array([[6, 7]]),
 array([[ 7],
        [12]]),
 array([[13, 14]]))

In [10]:
m[-2:,:2]

array([[ 5,  6],
       [10, 11]])

In [25]:
# 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.
# 1)이 배열에서 3의 배수를 찾아라.
# 2)이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# 3)이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

f = m.flatten()
f[f % 3 == 0], f[f % 4 == 1], f[np.logical_and(f % 3 == 0, f % 4 == 1)]

(array([ 0,  3,  6,  9, 12]), array([ 1,  5,  9, 13]), array([9]))

In [28]:
# 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오.
# 2, 1, 0, 0, 0 
# 3, 2, 1, 0, 0 
# 0, 3, 2, 1, 0 
# 0, 0, 3, 2, 1 
# 0, 0, 0, 3, 2

#positional arg가 항상 keyword arg (N=~)보다 먼저 와야함
np.eye(5,5,k=0, dtype=int) * 2 + np.eye(5,5,k=-1, dtype=int) * 3 + np.eye(5,5,k=1, dtype=int)

array([[2, 1, 0, 0, 0],
       [3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2]])

In [13]:
# 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 
# 이 데이터에 대해 다음과 같은 값을 구하시오.
# 1)전체의 최댓값
# 2)각 행의 합
# 3)각 행의 최댓값
# 4)각 열의 평균
# 5)각 열의 최솟값

np.random.seed(2022)
b = np.random.uniform(0,11,30).reshape(5,6).round(4)
b

array([[ 0.1029,  5.4896,  1.2472,  0.5497,  7.5395,  5.3569],
       [ 9.8742,  7.122 ,  9.8666,  7.9325,  9.1449,  9.1032],
       [ 9.1694, 10.5275,  4.0485,  5.4432,  3.7346,  6.8137],
       [10.7528,  1.0608,  8.1863,  3.2175,  3.2854,  8.2772],
       [ 0.2053,  5.7611,  9.5088,  4.2773,  2.3341,  5.227 ]])

In [14]:
b.max()

10.7528

In [15]:
b.sum(axis=1)

array([20.2858, 53.0434, 39.7369, 34.78  , 27.3136])

In [16]:
b.max(axis=1)

array([ 7.5395,  9.8742, 10.5275, 10.7528,  9.5088])

In [17]:
b.mean(axis=0)

array([6.02092, 5.9922 , 6.57148, 4.28404, 5.2077 , 6.9556 ])

In [18]:
b.min(axis=0)

array([0.1029, 1.0608, 1.2472, 0.5497, 2.3341, 5.227 ])

In [26]:
# 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 
# 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 
# 각 열(column)을 재정렬하시오. 
# array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])

score = np.array([[ 1, 2, 3, 4], [ 46, 99, 100, 71], [ 81, 59, 90, 100]])
score
#np.sort(score, axis=1)[::-1]


array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [27]:
indices = np.argsort(score[1])
indices

array([0, 3, 1, 2], dtype=int64)

In [28]:
indices[::-1]

array([2, 1, 3, 0], dtype=int64)

In [29]:
score[:, indices[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [30]:
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [32]:
# 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 
# 던져서 나오는 숫자의 평균을 구하시오.

np.random.seed(2022)
dice = np.random.randint(1,7,100)
dice

array([6, 5, 6, 1, 2, 2, 1, 1, 3, 1, 1, 6, 2, 2, 4, 4, 4, 1, 4, 1, 4, 1,
       6, 1, 3, 3, 4, 2, 3, 1, 6, 6, 2, 6, 6, 5, 1, 3, 3, 3, 4, 5, 6, 2,
       3, 5, 1, 6, 6, 5, 3, 6, 1, 6, 6, 6, 6, 6, 1, 4, 4, 3, 5, 1, 2, 5,
       2, 1, 6, 6, 1, 1, 4, 2, 6, 4, 3, 2, 6, 3, 2, 5, 2, 3, 3, 2, 6, 2,
       3, 2, 5, 4, 1, 5, 5, 5, 5, 1, 2, 3])

In [33]:
np.mean(dice)

3.47

In [34]:
# duce array에서의 고유값
np.unique(dice)

array([1, 2, 3, 4, 5, 6])

In [35]:
# dice array에서 고유값 및 그 갯수
np.unique(dice, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([20, 17, 16, 12, 13, 22], dtype=int64))

In [36]:
unique, counts = np.unique(dice, return_counts=True)
dict(zip(unique, counts))

{1: 20, 2: 17, 3: 16, 4: 12, 5: 13, 6: 22}

In [37]:
# 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 
# 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 
# 250일 동안의 주가를 무작위로 생성하시오.

#10000 * ((100 + np.random.randn(250))/100)

In [40]:
# 5개만 먼저 테스트
np.random.seed(2022)
rate = np.random.normal(0,0.01,5)
price = 10000
for i in range(5):
    price = np.round(price * (1 + rate[i]))
    print(int(price), end=' ')

10000 9973 9959 10157 10186 

In [41]:
# 위에서 구한 이자율(%)
rate * 100

array([-5.27899086e-04, -2.74901425e-01, -1.39285562e-01,  1.98468616e+00,
        2.82109326e-01])

In [44]:
# 250개 정규분포, list 활용
np.random.seed(2022)
rate = np.random.normal(0,0.01,250)
price = 10000
price_list = []
for i in range(250):
    price = price + np.round(price * rate[i])
    price_list.append(price)

price_array = np.array(price_list, dtype=np.int32)
price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [46]:
# 정규분포, array 활용
np.random.seed(2022)
rate = np.random.normal(0,0.01,250)
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price * rate[i])
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])

In [47]:
np.random.seed(2022)
rate = np.random.randn(250)         # %가 아니라 숫자로 나오므로 뒤에 0.01 곱해주면 됨
price = 10000
price_array = np.empty(250, dtype=np.int32)

for i in range(250):
    price = price + np.round(price * rate[i]*0.01)          #여기
    price_array[i] = price

price_array[-10:]

array([10916, 10834, 10753, 10838, 10950, 11089, 11006, 11182, 11360,
       11658])